spring:
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_shop_db
    username: demo_shop_user
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    user: demo_shop_user
    password: 12345
    change-log: classpath:liquibase/changelog/changelog.yaml



#changelogFile: ./changelog/changelog.yaml
#driver: org.postgresql.Driver
#url: jdbc:postgresql://localhost:5432/demo_shop_db
#username: demo_shop_user
#password: 12345